# Configurar el servicio de MySQL y Apache en Gitpod
image:
  file: Dockerfile

# Definir las tareas iniciales al abrir el workspace
tasks:
  - name: Iniciar Apache y MySQL
    init: |
      sudo service apache2 start
      sudo service mysql start
      sudo mysql -u root -e "CREATE DATABASE magento;"
      sudo mysql -u root -e "CREATE USER 'magentouser'@'localhost' IDENTIFIED BY 'password123';"
      sudo mysql -u root -e "GRANT ALL PRIVILEGES ON magento.* TO 'magentouser'@'localhost';"
      sudo mysql -u root -e "FLUSH PRIVILEGES;"
    command: |
      cd /workspace/magento
      composer install

# Definir los puertos que Gitpod expondrá
ports:
  - port: 80
    onOpen: open-browser

# Variables de entorno (opcional)
env:
  MYSQL_ROOT_PASSWORD: password123
