tasks:
    setup:
        name: Setup Project
        description: Setup the environment and dependencies for Magento
        command: |
            sudo service apache2 start
            sudo service mysql start
            sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS magento;"
            sudo mysql -u root -e "CREATE USER IF NOT EXISTS 'magentouser'@'localhost' IDENTIFIED BY 'password123';"
            sudo mysql -u root -e "GRANT ALL PRIVILEGES ON magento.* TO 'magentouser'@'localhost';"
            sudo mysql -u root -e "FLUSH PRIVILEGES;"
            cd /workspace/magento
            composer install
        triggeredBy:
        - postEnvironmentStart  # Esto asegura que se ejecuta cuando inicias el entorno

services:
    backend:
        name: Backend Service (Apache & MySQL)
        description: Starts Apache and MySQL services for Magento development
        commands:
            start: |
                echo "Starting backend services (Apache & MySQL)..."
                sudo service apache2 start
                sudo service mysql start
                touch /tmp/backend.started
                while true; do
                    sleep 1
                    date
                done
            ready: |
                if sudo service apache2 status | grep running && sudo service mysql status | grep running; then
                    echo "Backend services (Apache & MySQL) are ready"
                    exit 0
                else
                    echo "Backend services are not ready"
                    exit 1
                fi
        triggeredBy:
        - postEnvironmentStart  # Se ejecuta automáticamente tras iniciar el entorno
